version: "3"
services:
    app:
        container_name: app
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        expose:
            - 9000
        volumes:
            - .:/usr/src/app
            - ./public:/usr/src/app/public
        depends_on:
            - mysql
        networks:
            - app_network

    nginx:
        container_name: nginx
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        volumes:
            - ./public:/usr/src/app/public
        ports:
            - 8000:80
        depends_on:
            - app
        environment:
            NGINX_FPM_HOST: app
            NGINX_ROOT: /usr/src/app/public
        networks:
            - app_network

    mysql:
        image: mysql
        container_name: mysql
        restart: always
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: instagram-db
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        volumes:
             - mysql:/var/lib/mysql
    phpmyadmin:
        image: arm64v8/phpmyadmin
        container_name: phpmyadmin
        links:
            -  mysql
        restart: always
        ports:
            - 8080:80
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
volumes:
    mysql:
        driver: local
networks:
    app_network:
        external:
            name: app_gateway
